version: '3'
services:
  dev:
    build: .
    volumes:
      - .:/workspace
  mysql:
    image: mysql:5.7.26
    volumes:
      - ./db/init.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: db
